(()=>{
const mapUrl=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const D=[
{date:'2026-07-15',dow:'三',area:'移動日',title:'抵達大阪，直接回飯店休息',tags:['移動為主','不排景點','22:00入住'],note:'抵達後只做入住與便利商店補給，保留孩子睡眠。',stops:[['13:00','新竹住家接車','3 人、28 吋行李 ×2、背包 ×2、2 歲 5 個月兒童安全座椅。','新竹縣竹北市勝利十一街'],['16:25','IT212 桃園起飛','第一航廈；預留用餐與上廁所時間。','桃園國際機場第一航廈'],['20:15','抵達關西機場','入境、領行李後聯絡接機司機。','関西国際空港 第1ターミナル'],['約22:00','VESSEL INN NAMBA 入住','簡單補給、洗澡後直接休息。','VESSEL INN NAMBA']]},
{date:'2026-07-16',dow:'四',area:'京都',title:'三十三間堂、下鴨神社與上賀茂神社',tags:['神社慢旅','推車可行','20:00回飯店'],note:'上午先看三十三間堂；中午到下鴨神社與糺之森，鴨川三角洲讓孩子短暫放電。午後安排冷氣午休，再前往上賀茂神社。',stops:[['08:00','難波出發','帶水、遮陽帽、替換上衣與薄外套。','VESSEL INN NAMBA'],['09:30','三十三間堂','室內參觀約 60–75 分鐘；推車依現場規定停放。','三十三間堂'],['11:15','下鴨神社・糺之森','林蔭較多，但仍控制步行時間。','下鴨神社'],['12:20','鴨川三角洲','短暫放電與午餐；炎熱時直接縮短。','鴨川デルタ'],['13:00–15:00','午餐與午睡','優先找有冷氣、可坐久的餐廳或商場。','出町柳駅'],['15:30','上賀茂神社','保留 60–75 分鐘；體力不足可取消。','上賀茂神社'],['17:45','京都車站 Porta 晚餐','室內吃飯、補水、整理推車。','京都ポルタ'],['20:00','回到 VESSEL INN NAMBA','不追加夜間景點。','VESSEL INN NAMBA']]},
{date:'2026-07-17',dow:'五',area:'神戶',title:'南京町、麵包超人與 Harborland',tags:['親子主場','室內避暑','20:00回飯店'],note:'神戶舊居留地與南京町放上午，午後以神戶麵包超人兒童博物館為主場。átoa 僅作雨天替代，不與麵包超人同日硬塞。',stops:[['08:45','難波出發前往神戶','推車走平坦港區線。','VESSEL INN NAMBA'],['10:00','神戶舊居留地','短走建築街景，炎熱時縮短。','神戸旧居留地'],['11:00','南京町早午餐','避開正午尖峰，選有座位店家。','南京町 神戸'],['12:30–15:30','神戶麵包超人兒童博物館','2 歲 5 個月孩子主場與午睡緩衝。','神戸アンパンマンこどもミュージアム＆モール'],['16:00','Harborland・MOSAIC','室內休息、港景與簡單購物。','神戸ハーバーランド'],['17:45','MOSAIC 晚餐','看港景收尾，不等待額外表演。','神戸ハーバーランド umie モザイク'],['20:00','回到 VESSEL INN NAMBA','若孩子疲累，18:30 前直接返程。','VESSEL INN NAMBA']]},
{date:'2026-07-18',dow:'六',area:'日本橋',title:'模型與二手店，保留完整找貨時間',tags:['模型主場','午後室內','19:30回飯店'],note:'先看新品市場價，再比較二手盒況。單點刪減，不追求每家打卡。',stops:[['10:00','Den Den Town 主街','先巡主力店面，建立價格基準。','日本橋でんでんタウン'],['10:30','Super Kids Land／Volks','新品、工具與耗材。','スーパーキッズランド本店'],['12:30','室內午餐與午睡','找有座位、冷氣與推車空間的店。','なんばCITY'],['14:30','Mandarake／駿河屋','二手收藏、盒況與價格比較。','まんだらけ グランドカオス'],['16:30','Jungle 空想的機械館','機器人、特攝與機械類。','ジャングル 空想的機械館'],['18:30','千日前晚餐','整理照片與價格後回飯店。','千日前商店街'],['19:30','回到 VESSEL INN NAMBA','','VESSEL INN NAMBA']]},
{date:'2026-07-19',dow:'日',area:'池田・梅田',title:'杯麵博物館與梅田室內行程',tags:['親子體驗','室內','20:00回飯店'],note:'上午前往池田的杯麵博物館，午後移到梅田商場休息。體驗活動與營業狀況以當日現場為準。',stops:[['09:00','難波出發前往池田','減少轉乘與戶外曝曬。','VESSEL INN NAMBA'],['10:15','安藤百福發明紀念館 大阪池田','親子參觀；熱門體驗可能需排隊或預約。','カップヌードルミュージアム 大阪池田'],['12:15','池田午餐','吃完後前往梅田，車上或商場午睡。','池田駅 大阪'],['14:00','Grand Front／LUCUA','冷氣、親子休息與選物。','グランフロント大阪'],['17:30','大阪 Station City 晚餐','明亮、交通方便，吃完直接回難波。','大阪ステーションシティ'],['20:00','回到 VESSEL INN NAMBA','','VESSEL INN NAMBA']]},
{date:'2026-07-20',dow:'一',area:'難波',title:'基地慢遊：Namba Parks、法善寺與道頓堀',tags:['不跨區','午睡友善','20:00回飯店'],note:'把原本 Day 2 的難波熟悉日移到後段。已去過的難波八阪神社不再安排，也不排高島屋。',stops:[['10:00','Namba Parks','室內商場為主，花園只在不熱時短走。','なんばパークス'],['12:00','Namba City 午餐','用餐後安排推車午睡。','なんばCITY'],['13:00–15:00','午睡與室內休息','BicCamera 或地下街依需求選一處。','ビックカメラなんば店'],['16:30','法善寺橫丁','短距離散步與拍照。','法善寺横丁'],['17:30','千日前・道頓堀晚餐','在人多但明亮的區域收尾。','道頓堀'],['20:00','回到 VESSEL INN NAMBA','','VESSEL INN NAMBA']]},
{date:'2026-07-21',dow:'二',area:'心齋橋・堀江',title:'Orange Street、美國村與心齋橋',tags:['設計街區','午後室內','20:00回飯店'],note:'上午晚一點出門，最熱時段留在商場。Orange Street 與美國村只抓重點，不從頭走到底。',stops:[['10:30','心齋橋 PARCO','挑明確樓層，不做全館硬逛。','心斎橋PARCO'],['12:30','商場午餐與午睡','冷氣休息到午後熱度下降。','心斎橋PARCO'],['15:30','Orange Street','設計店與路面店，控制在 60–90 分鐘。','オレンジストリート 大阪'],['17:00','美國村・心齋橋筋','依體力選一段散步。','アメリカ村'],['18:30','心齋橋或難波晚餐','不追加跨區夜景。','心斎橋筋商店街'],['20:00','回到 VESSEL INN NAMBA','','VESSEL INN NAMBA']]},
{date:'2026-07-22',dow:'三',area:'宇治・難波',title:'宇治半日，回難波完成最後採買與打包',tags:['平等院','抹茶','20:20回飯店'],note:'宇治只做半日主線，午後回大阪午睡與最後採買。所有退稅、液體與冷藏品今晚完成。',stops:[['08:30','難波出發前往宇治','','VESSEL INN NAMBA'],['10:00','平等院','控制戶外時間，依孩子狀況決定是否進博物館。','平等院'],['11:30','宇治橋與表參道午餐','抹茶與和菓子以當日食用或常溫品為主。','宇治橋通り商店街'],['13:00','返回大阪','車上或回飯店午睡。','VESSEL INN NAMBA'],['15:30','難波最後採買','Namba City、Namba Walk、BicCamera；只買清單品。','なんばウォーク'],['18:30','道頓堀最後晚餐','用餐後回飯店打包。','道頓堀'],['20:20','回飯店完成打包','護照、退稅品、兒童用品與明早隨身物分開。','VESSEL INN NAMBA']]},
{date:'2026-07-23',dow:'四',area:'回程',title:'直接前往機場',tags:['早起','不補買','11:45起飛'],note:'建議 07:30–07:45 從飯店出發。今天不安排臨空城 Outlet 或市區補買。',stops:[['06:45','起床與最後檢查','護照、手機、充電線、退稅品、兒童用品。','VESSEL INN NAMBA'],['07:30–07:45','飯店接車','退房後直接前往 KIX。','VESSEL INN NAMBA'],['約09:00','抵達關西機場','報到、托運、安檢與早餐。','関西国際空港 第1ターミナル'],['11:45','IT211 起飛','預計 13:45 抵達桃園。','桃園國際機場第一航廈']]}
];
function render(){const root=document.getElementById('daysList');if(!root)return;root.innerHTML=D.map((d,i)=>`<details class="day-card" ${i===1?'open':''}><summary><div class="day-num"><div><b>${d.date.slice(-2)}</b><small>DAY ${i+1}</small></div></div><div class="day-summary"><h3>${d.title}</h3><p>${d.area} · 週${d.dow}</p></div><div class="chev">⌄</div></summary><div class="day-body"><div class="day-rhythm">${d.tags.map(t=>`<span class="pill">${t}</span>`).join('')}</div><div class="timeline">${d.stops.map(s=>`<div class="stop"><div class="stop-time">${s[0]}</div><div class="stop-dot"></div><div class="stop-content"><b>${s[1]}</b><p>${s[2]}</p>${s[3]?`<div class="stop-links"><a class="mini-link" target="_blank" rel="noopener" href="${mapUrl(s[3])}">📍 地圖</a></div>`:''}</div></div>`).join('')}</div><div class="day-note">💡 ${d.note}</div></div></details>`).join('')}
function polish(){document.title='風起，慢行。｜2026 關西親子慢旅';document.querySelectorAll('.brand-copy strong').forEach((e,i)=>{if(i===0)e.textContent='風起，慢行。'});const h=document.querySelector('.hero h1');if(h)h.innerHTML='風起，<br>慢行。';const eye=document.querySelector('.hero .eyebrow');if(eye)eye.textContent='OSAKA · KYOTO · KOBE';const jp=document.querySelector('.hero .jp');if(jp)jp.textContent='大阪・京都・神戶，三人九日的盛夏散步';const note=document.querySelector('.hero-note');if(note)note.textContent='帶著 2 歲 5 個月的小旅伴，上午看一個主景點，午後安排冷氣與午睡，晚上在明亮熱鬧的區域吃飯，再回到 VESSEL INN NAMBA。';const ext=document.querySelector('.extension-wrap');if(ext)ext.remove();const intro=document.querySelector('#itinerary .page-intro');if(intro)intro.innerHTML='<h1>一天一主場，午後留給孩子休息。</h1><p>京都、神戶與大阪分日安排；最晚約 20:00–20:20 回到 VESSEL INN NAMBA。</p>';const today=document.getElementById('todayCard');const now=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});const d=D.find(x=>x.date===now)||D[1];if(today)today.innerHTML=`<div class="today-route"><div class="today-date"><b>${Number(d.date.slice(-2))}</b><span>JUL · 週${d.dow}</span></div><div class="today-main"><h3>${d.title}</h3><p>${d.note}</p><div class="route-pills">${d.tags.map((t,i)=>`<span class="pill ${i===0?'coral':i===1?'teal':'mustard'}">${t}</span>`).join('')}</div></div></div>`}
function cleanShopping(){document.querySelectorAll('.check-copy span').forEach(e=>{e.textContent=e.textContent.replaceAll('高島屋','難波地下街')});document.querySelectorAll('.check-copy b').forEach(e=>{if(e.textContent.includes('高島屋'))e.textContent=e.textContent.replaceAll('高島屋','難波地下街')})}
function run(){render();polish();cleanShopping()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();setTimeout(run,300);
})();