(()=>{
const mapUrl=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const D=[
{date:'2026-07-15',dow:'三',area:'移動日',title:'從家門到難波',tags:['2 大 1 小','不塞景點','早點休息'],note:'20:15 抵達關西機場，第一晚只接機、入住與簡單補給。',stops:[['13:00','新竹住家接車','28 吋行李 ×2、背包 ×2、2 歲 5 個月兒童安全座椅。','新竹'],['16:25','IT212 桃園起飛','預留吃飯、換尿布與安檢緩衝。','桃園國際機場第一航廈'],['20:15','抵達關西機場','領行李後聯絡司機。','関西国際空港 第1ターミナル'],['約22:00','VESSEL INN NAMBA 入住','便利商店補給後直接休息。','VESSEL INN NAMBA']]},
{date:'2026-07-16',dow:'四',area:'難波',title:'先熟悉基地，再慢慢逛',tags:['推車友善','午後室內','熱鬧夜街'],note:'第一個完整日不跨區。18:00 後只走千日前、道頓堀等熱鬧且可快速回飯店的區域，20:00 前回 VESSEL。',stops:[['10:00','高島屋 B1 偵查','先看伴手禮、甜點與退稅動線。','大阪高島屋'],['11:30','Namba City','午餐與室內逛街。','なんばCITY'],['14:00','Namba Parks','冷氣、咖啡與午睡緩衝。','なんばパークス'],['17:00','Parks Garden 短散步','陽光轉弱後再走戶外。','なんばパークス パークスガーデン'],['18:15','千日前／道頓堀','有燈、有餐廳、離飯店近。','千日前商店街'],['約19:50','回到 VESSEL','不再追加遠端夜景。','VESSEL INN NAMBA']]},
{date:'2026-07-17',dow:'五',area:'京都文化日',title:'三十三間堂與上賀茂神社',tags:['京都保留','午睡優先','20:00回飯店'],note:'三十三間堂必留；上賀茂神社依午睡、氣溫與孩子精神決定。晚間只停京都站／Porta，不去偏遠夜遊。',stops:[['08:15','難波出發','提早避開高溫與人潮。','大阪難波駅'],['09:45','三十三間堂','室內文化主場，停留約 60–90 分鐘。','三十三間堂'],['11:45','京都站午餐與午睡','Porta／The CUBE，完整休息。','京都駅'],['14:15','上賀茂神社','高溫或午睡不穩就取消。','上賀茂神社'],['17:00','京都站晚餐','熱鬧、室內、親子設備集中。','京都駅'],['18:15','最晚離開京都','預留推車轉乘時間。','京都駅'],['約20:00','回到 VESSEL','回飯店後直接洗澡休息。','VESSEL INN NAMBA']]},
{date:'2026-07-18',dow:'六',area:'神戶港區',title:'麵包超人、南京町與港邊晚風',tags:['2歲主場','午後室內','Harborland'],note:'麵包超人博物館是本日主場。átoa 改為雨天或角色興趣不足時替代，不與麵包超人同日硬塞。18:50 前離開神戶。',stops:[['08:50','難波前往元町','推車優先。','元町駅 神戸'],['10:10','神戶舊居留地短散步','平坦好走，控制 45–60 分鐘。','神戸旧居留地'],['11:20','南京町午餐','提早吃飯避開人潮。','南京町 神戸'],['12:45','神戶麵包超人兒童博物館','2 歲 5 個月主場，預留 2.5–3 小時。','神戸アンパンマンこどもミュージアム'],['16:15','Harborland／MOSAIC','親子商場、港邊散步與早晚餐。','神戸ハーバーランド'],['17:45','神戶港塔外觀','登塔只在無排隊且孩子精神好時選配。','神戸ポートタワー'],['18:50','最晚離開神戶','不等 Night Mirage、不加遊船。','高速神戸駅'],['約20:00','回到 VESSEL','有精神才在千日前短走。','VESSEL INN NAMBA']]},
{date:'2026-07-19',dow:'日',area:'心齋橋・堀江',title:'兩個跨城日後，留一個輕鬆下午',tags:['晚點出門','室內優先','熱鬧街區'],note:'只走心齋橋 PARCO、心齋橋筋與 Orange Street。晚間回道頓堀或千日前，約 19:30 回 VESSEL。',stops:[['10:30','心齋橋 PARCO／大丸','室內主場，先補親子休息。','心斎橋PARCO'],['14:00','心齋橋筋重點快逛','避開長時間停留在人潮最密處。','心斎橋筋商店街'],['16:00','Orange Street','依氣溫縮短戶外段。','オレンジストリート 大阪'],['18:15','道頓堀／千日前晚餐','熱鬧且撤退容易。','道頓堀'],['約19:30','回到 VESSEL','整理戰利品與早休息。','VESSEL INN NAMBA']]},
{date:'2026-07-20',dow:'一',area:'池田＋梅田',title:'畫一杯泡麵，再回城市逛街',tags:['親子手作','午睡緩衝','梅田室內'],note:'上午杯麵博物館，下午回梅田；不再加箕面或勝尾寺。18:45 前離開梅田，約 19:30 回 VESSEL。',stops:[['09:00','難波前往池田','早餐與推車先準備好。','カップヌードルミュージアム 大阪池田'],['10:15','杯麵博物館','孩子主要畫杯身，不把完整 DIY 當必達。','カップヌードルミュージアム 大阪池田'],['12:15','池田站附近午餐','坐下、換尿布、補水。','池田駅 大阪'],['13:30','前往梅田／午睡','利用移動安排午睡。','大阪駅'],['14:30','Grand Front Osaka','推車友善，大人輪流逛。','グランフロント大阪'],['16:30','LUCUA 或 Yodobashi 擇一','只選一個主場。','LUCUA大阪'],['18:45','最晚離開梅田','摩天輪只在無排隊時選配。','大阪梅田駅'],['約19:30','回到 VESSEL','晚間散步留給道頓堀、千日前。','VESSEL INN NAMBA']]},
{date:'2026-07-21',dow:'二',area:'日本橋',title:'模型與二手店主場',tags:['留足找貨時間','可回飯店午睡','不跨區'],note:'離飯店近，適合大人輪流逛、小朋友回房午睡。高價品至少比兩家。',stops:[['10:00','Den Den Town','先建立新品價格基準。','日本橋でんでんタウン'],['10:30','Super Kids Land／Volks','新品、工具與耗材。','ジョーシンスーパーキッズランド本店'],['12:30','回難波午餐／午睡','必要時先把戰利品放回飯店。','VESSEL INN NAMBA'],['14:30','Mandarake／駿河屋','確認盒況與缺件。','まんだらけ グランドカオス'],['16:30','Jungle 空想的機械館','特攝與收藏品。','ジャングル大阪日本橋店'],['18:30','千日前晚餐','約 19:30 回飯店。','千日前商店街']]},
{date:'2026-07-22',dow:'三',area:'宇治＋難波',title:'平等院半日，最後補貨',tags:['獨立半日','午後回基地','完成打包'],note:'宇治只排半日；午後回難波採購、退稅與打包。臨空城 Outlet 不排。',stops:[['08:30','前往宇治','推車與防曬準備。','宇治駅'],['10:15','平等院','高溫時縮短庭園段。','平等院'],['11:45','宇治表參道午餐','抹茶、冷氣與休息。','宇治橋通り商店街'],['13:30','返回難波','不繞回京都市區。','大阪難波駅'],['16:00','高島屋 B1 最後補貨','冷藏、排隊與退稅一次完成。','大阪高島屋'],['19:30','回 VESSEL 打包','確認行李重量與文件。','VESSEL INN NAMBA']]},
{date:'2026-07-23',dow:'四',area:'回程',title:'直接去機場',tags:['不補買','不排Outlet','提早報到'],note:'11:45 國際航班，早上不安排難波或臨空城。',stops:[['06:45','起床與最後確認','護照、兒童用品、充電器。','VESSEL INN NAMBA'],['07:30','飯店接車','時間再與司機確認。','VESSEL INN NAMBA'],['約09:00','抵達 KIX','報到、托運、安檢與早餐。','関西国際空港 第1ターミナル'],['11:45','IT211 起飛','KIX → TPE。','関西国際空港']]}
];
function render(){const root=document.getElementById('daysList');if(!root)return;root.innerHTML=D.map((d,i)=>`<details class="day-card" ${i===2||i===3?'open':''}><summary><div class="day-num"><div><b>${d.date.slice(-2)}</b><small>DAY ${i+1}</small></div></div><div class="day-summary"><h3>${d.title}</h3><p>${d.area} · 週${d.dow}</p></div><div class="chev">⌄</div></summary><div class="day-body"><div class="day-rhythm">${d.tags.map(t=>`<span class="pill">${t}</span>`).join('')}</div><div class="timeline">${d.stops.map(s=>`<div class="stop"><div class="stop-time">${s[0]}</div><div class="stop-dot"></div><div class="stop-content"><b>${s[1]}</b><p>${s[2]}</p><div class="stop-links"><a class="mini-link" target="_blank" rel="noopener" href="${mapUrl(s[3])}">📍 地圖</a></div></div></div>`).join('')}</div><div class="day-note">${d.note}</div></div></details>`).join('')}
function polish(){document.title='風起，慢行。｜2026 關西九日親子旅';document.querySelectorAll('.brand-copy strong').forEach((e,i)=>{if(i===0)e.textContent='風起，慢行。'});const h=document.querySelector('.hero h1');if(h)h.innerHTML='風起，<br>慢行。';const jp=document.querySelector('.hero .jp');if(jp)jp.textContent='大阪・京都・神戶，三人九日的盛夏散步';const note=document.querySelector('.hero-note');if(note)note.textContent='帶著 2 歲 5 個月的小旅伴，上午看一座城，午後留給冷氣與午睡，夜裡回到熱鬧卻熟悉的難波。這趟不追景點，只把值得的風景慢慢留下。';const ext=document.querySelector('.extension-wrap');if(ext)ext.remove();const intro=document.querySelector('#itinerary .page-intro p');if(intro)intro.textContent='京都保留、神戶以幼兒主場重排；每天標示最晚離開與回到 VESSEL INN NAMBA 的時間。';render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',polish);else polish();
})();